version: 2
jobs:
  build:
    filters:
        branches:
            only:
                - ci
                - master
    docker:
      - image: openjdk:11
    environment:
      SBT_VERSION: 1.3.13
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
      - run:
          name: Compile
          command: sbt compile
      - run:
          name: Test
          command: sbt test
