package model.sim

import scala.collection.mutable

// Assume all parameters are the default generated by JSimGraph, we'll add parameters next week
sealed trait Node
case object Source extends Node
case object Queue extends Node
case object Sink extends Node
case object Fork extends Node
case object Join extends Node

case class Connection(source: Node, target: Node)

case class UserClass(name: String, priority: Int, referenceSource: Node, `type`: UserClass.Type)

object UserClass {
  sealed trait Type
  case object Open
  case object Closed
}

case class Measure(alpha: Float, referenceNode: Node, referenceClass: UserClass, `type`: String, verbose: Boolean)

case class Sim(nodes: Set[Node],
               connections: Set[Connection],
               classes: Set[UserClass],
               measures: Set[Measure],
               configuration: Sim.Configuration = mutable.HashMap.empty)

object Sim {
  type Configuration = mutable.HashMap[String, Any]
}